%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Mihir\Desktop\Group14_FinalProject\Project Work\ramen-ratings.csv
%
% Auto-generated by MATLAB on 07-Dec-2019 00:51:21

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Review", "Brand", "Variety", "Style", "Country", "Stars", "TopTen"];
opts.VariableTypes = ["double", "categorical", "string", "categorical", "categorical", "double", "string"];
opts = setvaropts(opts, [3, 7], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [2, 3, 4, 5, 7], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\Mihir\Desktop\Group14_FinalProject\Project Work\ramen-ratings.csv", opts);

%% Convert to output type
Review = tbl.Review;
Brand = tbl.Brand;
Variety = tbl.Variety;
Style = tbl.Style;
Country = tbl.Country;
Stars = tbl.Stars;
TopTen = tbl.TopTen;

%% Clear temporary variables
clear opts tbl